#!/usr/bin/env bash
# agentfence - guardrails for AI coding agents on shared Linux hosts.
#
# Self-contained. Copy this one file to a node and run it. Needs bash,
# coreutils and python3; nothing else, and no network access.
#
#   ./agentfence              what is on this node vs what should be
#   ./agentfence apply        make the node match. Asks first.
#   ./agentfence init         write the defaults out so you can edit them
#   ./agentfence config       the settings a run would use, and where from
#   ./agentfence doctor       checks, shim resolution, and cplt doctor
#   ./agentfence uninstall    remove everything it installed
#
#   --config FILE   site settings; see "Settings" in README.md
#   --policy-dir DIR  site policy laid over the shipped one
#   --yes           do not ask
#   --role login|compute|auto        default auto
#   --nodes "a b c" do the same on those hosts over ssh
#   --no-packages   do not install bubblewrap or cplt
#
# Exit status: 0 the node matches, 1 it does not (status only), 2 something
# went wrong. So `agentfence || alert` works from cron.
#
# Built from the agentfence repository. Regenerate with `make dist`;
# do not edit this file by hand.
set -uo pipefail

VERSION="@@VERSION@@"
BUILT="@@BUILT@@"

readonly E_OK=0 E_DRIFT=1 E_FAIL=2

ACTION=status ROLE=auto ASSUME_YES=0 DO_PACKAGES=1 NODES="" CONFIG_FILE="" POLICY_DIR_ARG=""
WORK="" FAILED=0

# --------------------------------------------------------------------- output
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
    C_OK=$'\033[32m'; C_CHG=$'\033[33m'; C_ERR=$'\033[31m'; C_B=$'\033[1m'; C_0=$'\033[0m'
else
    C_OK=""; C_CHG=""; C_ERR=""; C_B=""; C_0=""
fi
say()     { printf '%s\n' "$*"; }
heading() { printf '\n%s%s%s\n' "$C_B" "$*" "$C_0"; }
same()    { printf '  %s=%s %s\n'  "$C_OK"  "$C_0" "$*"; }
change()  { printf '  %s>%s %s\n'  "$C_CHG" "$C_0" "$*"; }
note()    { printf '  %s-%s %s\n'  "$C_CHG" "$C_0" "$*"; }
problem() { printf '  %s!%s %s\n'  "$C_ERR" "$C_0" "$*" >&2; FAILED=1; }
die()     { printf '%s!%s %s\n'    "$C_ERR" "$C_0" "$*" >&2; exit $E_FAIL; }

trap '[ -n "$WORK" ] && rm -rf "$WORK"' EXIT

# ----------------------------------------------------------------------- args
while [ $# -gt 0 ]; do
    case "$1" in
        status|apply|uninstall|config|init|doctor) ACTION="$1" ;;
        --config)      CONFIG_FILE="${2:?--config needs a file}"; shift ;;
        --policy-dir)  POLICY_DIR_ARG="${2:?--policy-dir needs a directory}"; shift ;;
        --role)        ROLE="${2:?--role needs a value}"; shift ;;
        --nodes)       NODES="${2:?--nodes needs a value}"; shift ;;
        --yes|-y)      ASSUME_YES=1 ;;
        --no-packages) DO_PACKAGES=0 ;;
        --version)     say "agentfence $VERSION (built $BUILT)"; exit $E_OK ;;
        -h|--help)     sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'; exit $E_OK ;;
        *)             die "unknown argument: $1" ;;
    esac
    shift
done

# ------------------------------------------------------------ fan out to nodes
if [ -n "$NODES" ]; then
    rc=$E_OK
    for host in $NODES; do
        heading "=== $host ==="
        if ! scp -q "$0" "$host:/tmp/agentfence"; then
            problem "$host: could not copy the script"; rc=$E_FAIL; continue
        fi
        # The settings have to travel with it, or each node would fall back to
        # whatever it already had and the fleet would drift apart.
        if [ -n "$CONFIG_FILE" ] && ! scp -q "$CONFIG_FILE" "$host:/tmp/agentfence.conf"; then
            problem "$host: could not copy the config file"; rc=$E_FAIL; continue
        fi
        if [ -n "$POLICY_DIR_ARG" ] \
           && ! scp -qr "$POLICY_DIR_ARG" "$host:/tmp/agentfence-policy"; then
            problem "$host: could not copy the policy directory"; rc=$E_FAIL; continue
        fi
        ssh -t "$host" "sudo bash /tmp/agentfence $ACTION --role $ROLE \
            $([ -n "$CONFIG_FILE" ] && echo --config /tmp/agentfence.conf) \
            $([ -n "$POLICY_DIR_ARG" ] && echo --policy-dir /tmp/agentfence-policy) \
            $([ "$ASSUME_YES" = 1 ] && echo --yes) \
            $([ "$DO_PACKAGES" = 0 ] && echo --no-packages); \
            s=\$?; rm -rf /tmp/agentfence /tmp/agentfence.conf /tmp/agentfence-policy; exit \$s"
        case "$?" in 0) ;; 1) [ "$rc" = "$E_OK" ] && rc=$E_DRIFT ;; *) rc=$E_FAIL ;; esac
    done
    exit $rc
fi

# ------------------------------------------------------------- unpack payload
WORK="$(mktemp -d)" || die "could not create a temporary directory"
awk 'f{print} /^__PAYLOAD__$/{f=1}' "$0" | base64 -d | tar -xz -C "$WORK" \
    || die "the payload is corrupt; copy the script again"

# ------------------------------------------------------------------- settings
# Everything that differs between sites lives here, in one set of names. The
# same names work as environment variables, as lines in a --config file, and
# as lines in the file `apply` leaves on the node, so there is one vocabulary
# to learn rather than three.
#
# Precedence, highest first:
#   --config FILE            what you asked for on this run
#   the environment          AGENTFENCE_* already exported
#   /etc/agentfence/site.env what the last apply recorded here
#   the defaults below
#
# The recorded file is what makes `status` from cron stable: without it, a run
# with no variables set would report drift against the node every time and the
# exit code would be worthless.
SETTINGS="AGENTFENCE_SITE_NAME AGENTFENCE_SHARED_HOMES AGENTFENCE_SHARED_APPS \
AGENTFENCE_SHARED_WORKSPACES AGENTFENCE_MEMORY_HIGH AGENTFENCE_MEMORY_MAX \
AGENTFENCE_CPU_QUOTA AGENTFENCE_TASKS_MAX AGENTFENCE_SHIM_AGENTS \
AGENTFENCE_POLICY_DIR"

# Which layer each value came from, so `agentfence config` can show it. A
# setting that is not doing what an admin expects is nearly always one that
# was set somewhere else, and this is the only way to see that without
# guessing.
ORIGINS=""
set_origin() { ORIGINS="$ORIGINS$1=$2
"; }
origin_of() {
    local line
    while IFS= read -r line; do
        case "$line" in "$1="*) printf '%s' "${line#*=}"; return ;; esac
    done <<< "$ORIGINS"
    printf 'default'
}

# Anything already exported when we start came from the environment. Recorded
# before any file is read, because reading one overwrites the evidence.
for k in $SETTINGS; do
    [ -n "${!k:-}" ] && set_origin "$k" "environment"
done

# KEY=value only, and only keys we know. Never `source` a file as root: that
# would execute whatever is in it.
# mode: `override` for a file the user named on this run, which beats an
# ambient variable; `fill` for the node's recorded settings, which do not.
load_config() {
    local file="$1" required="$2" mode="$3" key value known
    if [ ! -r "$file" ]; then
        [ "$required" = required ] \
            && die "cannot read the config file: $file (create one with: agentfence init --config $file)"
        return 0
    fi
    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in ''|\#*) continue ;; esac
        key="${line%%=*}"; value="${line#*=}"
        key="${key%"${key##*[![:space:]]}"}"        # trim trailing space
        key="${key#"${key%%[![:space:]]*}"}"        # trim leading space
        value="${value#"${value%%[![:space:]]*}"}"  # trim leading space
        # A quoted value ends at its closing quote; anything after it is a
        # comment. The shipped example has inline comments, and without this a
        # cap parses as `16G"  # hard: ...`, which systemd rejects - leaving
        # the node with no cap at all and nothing saying so.
        case "$value" in
            \"*) value="${value#\"}"; value="${value%%\"*}" ;;
            \'*) value="${value#\'}"; value="${value%%\'*}" ;;
            *)   value="${value%%[[:space:]]#*}"
                 value="${value%"${value##*[![:space:]]}"}" ;;
        esac
        known=0
        for k in $SETTINGS; do [ "$k" = "$key" ] && known=1; done
        if [ "$known" = 0 ]; then
            note "ignoring unknown setting in $file: $key"
            continue
        fi
        if [ "$mode" = override ] || [ -z "${!key:-}" ]; then
            export "$key=$value"
            set_origin "$key" "$file"
        fi
    done < "$file"
}

[ -n "$CONFIG_FILE" ] && [ "$ACTION" != init ] && load_config "$CONFIG_FILE" required override
load_config /etc/agentfence/site.env optional fill

export AGENTFENCE_SHARED_HOMES="${AGENTFENCE_SHARED_HOMES:-}"
export AGENTFENCE_SHARED_APPS="${AGENTFENCE_SHARED_APPS:-}"
export AGENTFENCE_SHARED_WORKSPACES="${AGENTFENCE_SHARED_WORKSPACES:-}"
export AGENTFENCE_SITE_NAME="${AGENTFENCE_SITE_NAME:-This shared machine}"
export AGENTFENCE_MEMORY_HIGH="${AGENTFENCE_MEMORY_HIGH:-8G}"
export AGENTFENCE_MEMORY_MAX="${AGENTFENCE_MEMORY_MAX:-16G}"
export AGENTFENCE_CPU_QUOTA="${AGENTFENCE_CPU_QUOTA:-400%}"
export AGENTFENCE_TASKS_MAX="${AGENTFENCE_TASKS_MAX:-4096}"
# Every binary name cplt can launch, minus the ones that must not be shadowed.
# Taken from cplt's own src/agent.rs `binary_names()`, which is the source of
# truth; `deepseek` and `deepseek-harness` are spellings for --agent, not
# commands anything installs, so shimming them would shadow nothing.
#
# Deliberately absent:
#   claude  - Claude Code sandboxes itself from managed-settings.json, and
#             cplt sanitises the child environment, which breaks Claude Code's
#             CLAUDE_CODE_PROCESS_WRAPPER contract. Do not stack the two.
#   dsh     - the DeepSeek harness binary, but `dsh` is also distributed shell,
#             packaged on Debian and used on clusters. Shimming it would route
#             an admin's cluster command through an AI agent sandbox. Add it
#             with AGENTFENCE_SHIM_AGENTS if this site has no distributed shell.
export AGENTFENCE_SHIM_AGENTS="${AGENTFENCE_SHIM_AGENTS:-copilot opencode antigravity agy pi goose}"

# A shim goes on PATH ahead of the real binary, for every user on the node, so
# the name matters more than it looks. The shim ends in `cplt --agent <name>`,
# which means a name cplt cannot launch is broken anyway - and a name like
# `bash` or `cc` would shadow a system tool for everyone. Checking against
# cplt's own list catches both at install time rather than at a user's prompt.
SHIMMABLE="copilot opencode antigravity agy pi goose dsh"
for agent in $AGENTFENCE_SHIM_AGENTS; do
    case " $SHIMMABLE " in
        *" $agent "*) continue ;;
    esac
    case "$agent" in
        claude|cc|claude-code)
            die "refusing to shim '$agent': Claude Code sandboxes itself from /etc/claude-code/managed-settings.json, and cplt strips the environment its launcher needs. Do not stack the two." ;;
        shell|sh|bash|zsh|fish|dash|ksh)
            die "refusing to shim '$agent': that would put a shim ahead of the shell on every user's PATH." ;;
        *)
            die "refusing to shim '$agent': cplt cannot launch it, so the shim would fail when a user ran it. Known: $SHIMMABLE" ;;
    esac
done
export AGENTFENCE_POLICY_DIR="${AGENTFENCE_POLICY_DIR:-}"

# The flag is just the highest layer of the same setting.
if [ -n "$POLICY_DIR_ARG" ]; then
    export AGENTFENCE_POLICY_DIR="$POLICY_DIR_ARG"
    set_origin AGENTFENCE_POLICY_DIR "--policy-dir"
fi
POLICY_DIR="$AGENTFENCE_POLICY_DIR"
if [ -n "$POLICY_DIR" ] && [ "$ACTION" != init ]; then
    [ -d "$POLICY_DIR" ] \
        || die "policy directory not found: $POLICY_DIR (create one with: agentfence init --policy-dir $POLICY_DIR)"
    POLICY_DIR="$(cd "$POLICY_DIR" && pwd)"
fi
[ "$ACTION" = init ] && POLICY_DIR=""

# The shipped payload is the base policy; a site directory sits on top of it.
# A file named after a payload file replaces that file outright; the overlay
# JSON is merged into the shipped policy instead. Everything the installer
# reads goes through here, so there is one place that decides which wins.
policy_file() {
    if [ -n "$POLICY_DIR" ] && [ -f "$POLICY_DIR/$1" ]; then
        printf '%s' "$POLICY_DIR/$1"
    else
        printf '%s' "$WORK/$1"
    fi
}
policy_source() {
    if [ -n "$POLICY_DIR" ] && [ -f "$POLICY_DIR/$1" ]; then
        printf 'site'
    else
        printf 'shipped'
    fi
}
OVERLAY=""
[ -n "$POLICY_DIR" ] && [ -f "$POLICY_DIR/managed-settings.overlay.json" ] \
    && OVERLAY="$POLICY_DIR/managed-settings.overlay.json"

# Written back out so the next run, by anyone, sees the same settings. It is
# also a valid --config file, so a node can be copied to another node.
{
    printf '# Managed by agentfence. Written by `agentfence apply`.\n'
    printf '# A valid --config file: copy it to another node and pass it there.\n'
    printf '# Change a value by re-running apply with it set:\n'
    printf '#   agentfence apply --config ./agentfence.conf\n'
    printf '#   AGENTFENCE_SHARED_HOMES=/shared/home sudo -E agentfence apply\n'
    for key in $SETTINGS; do
        printf '%s="%s"\n' "$key" "${!key}"
    done
} > "$WORK/site.env"

# Fail before anything is printed or planned: a site path that cannot be used
# makes every later check meaningless.
python3 "$WORK/render-settings.py" "$(policy_file managed-settings.json)" $OVERLAY \
    > "$WORK/settings.rendered" \
    || die "check the policy and AGENTFENCE_SHARED_* paths above; nothing was changed"

# ----------------------------------------------------------------------- node
detect_role() {
    if command -v scontrol >/dev/null 2>&1 \
       && scontrol show node "$(hostname -s)" >/dev/null 2>&1; then
        echo compute
    elif systemctl is-active --quiet slurmd 2>/dev/null; then
        echo compute
    else
        echo login
    fi
}
[ "$ROLE" = auto ] && ROLE="$(detect_role)"
case "$ROLE" in login|compute) ;; *) die "--role must be login, compute or auto" ;; esac

# Something else already limits what one user can take on a login node
# (Arbiter2, Arbiter3, cgroup-warden, or a hand-written drop-in). If so we
# leave resource limits alone: two things managing the same slice is worse
# than one. Slurm is not a candidate - a login-node session is in no job.
find_existing_limiter() {
    local found=""
    systemctl list-unit-files 2>/dev/null \
        | grep -qE '^(arbiter2?|arbiter|cgroup-warden)\.service' && found="$found arbiter/cgroup-warden"
    for binary in arbiter arbiter2 cgroup-warden; do
        command -v "$binary" >/dev/null 2>&1 && found="$found $binary"
    done
    for dir in /etc/arbiter2 /etc/arbiter /etc/cgroup-warden; do
        [ -d "$dir" ] && found="$found $dir"
    done
    for f in /etc/systemd/system/user-.slice.d/*.conf; do
        [ -e "$f" ] || continue
        case "$f" in *50-agentfence-user-limits.conf) continue ;; esac
        found="$found $f"
    done
    printf '%s' "${found# }"
}
EXISTING_LIMITER="$(find_existing_limiter)"

# ------------------------------------------------------------- desired state
# One table. Each line: payload-file : destination : mode : roles : condition
# `condition` names a function that must succeed for the file to be wanted.
DESIRED_STATE="
site.env:/etc/agentfence/site.env:0644:login,compute:always
managed-settings.json:/etc/claude-code/managed-settings.json:0644:login,compute:always
50-agentfence-audit.rules:/etc/audit/rules.d/50-agentfence-audit.rules:0640:login,compute:always
cplt-config.toml:/etc/agentfence/cplt.toml:0644:login,compute:always
profile.d-agentfence.sh:/etc/profile.d/10-agentfence.sh:0644:login,compute:always
bin/agentfence-shim:/opt/agentfence/bin/agentfence-shim:0755:login,compute:always
50-agentfence-user-limits.conf:/etc/systemd/system/user-.slice.d/50-agentfence-user-limits.conf:0644:login:no_existing_limiter
50-agentfence-root-exempt.conf:/etc/systemd/system/user-0.slice.d/50-agentfence-root-exempt.conf:0644:login:no_existing_limiter
"
SHIM_DIR=/opt/agentfence/bin
SHIM_TARGET="$SHIM_DIR/agentfence-shim"

# A site directory may add files of its own. They are appended as ordinary
# rows, so they appear in the plan and are applied, reported and removed by
# exactly the same code as everything else - no second path to audit.
if [ -n "$POLICY_DIR" ] && [ -f "$POLICY_DIR/desired-state" ]; then
    while IFS=: read -r src dst mode roles condition; do
        case "$src" in ''|\#*) continue ;; esac
        [ -f "$POLICY_DIR/$src" ] || die "desired-state names a missing file: $src"
        case "$dst" in /*) ;; *) die "desired-state: destination must be absolute: $dst" ;; esac
        case "$mode" in [0-7][0-7][0-7]|[0-7][0-7][0-7][0-7]) ;;
            *) die "desired-state: mode must be octal, got: $mode" ;; esac
        DESIRED_STATE="$DESIRED_STATE$src:$dst:$mode:${roles:-login,compute}:${condition:-always}
"
    done < "$POLICY_DIR/desired-state"
fi

always()             { return 0; }
no_existing_limiter() { [ -z "$EXISTING_LIMITER" ]; }
wanted_on_role()      { case ",$1," in *",$ROLE,"*) return 0 ;; *) return 1 ;; esac; }

# Per-site values come from the environment rather than from editing the
# payload. One rendered file per source - a single shared temporary name would
# have two templated files overwrite each other.
# A site directory can do three things to a shipped file:
#   <name>                    replace it outright
#   <name>.append             add lines to the end of it
#   managed-settings.overlay.json   merge into the policy (JSON only)
# Append is the one an admin usually wants for the line-based files: adding an
# audit rule should not mean restating the rules that ship, which would then
# never pick up a later change to them.
render() {
    local source rendered="$WORK/.rendered.${1//\//_}" appended
    source="$(policy_file "$1")"
    appended="$POLICY_DIR/$1.append"
    case "$1" in
        managed-settings.json)
            # Built once at startup. Rendering here instead would put `die`
            # inside a command substitution, where it exits only the subshell
            # and the run carries on with an empty filename.
            printf '%s' "$WORK/settings.rendered" ;;
        site.env)
            printf '%s' "$WORK/site.env" ;;
        *)
            if grep -q '{{' "$source" 2>/dev/null; then
                sed -e "s|{{ memory_high }}|$AGENTFENCE_MEMORY_HIGH|g" \
                    -e "s|{{ memory_max }}|$AGENTFENCE_MEMORY_MAX|g" \
                    -e "s|{{ cpu_quota }}|$AGENTFENCE_CPU_QUOTA|g" \
                    -e "s|{{ tasks_max }}|$AGENTFENCE_TASKS_MAX|g" \
                    "$source" > "$rendered"
            elif [ -n "$POLICY_DIR" ] && [ -f "$appended" ]; then
                cat "$source" > "$rendered"
            else
                printf '%s' "$source"; return
            fi
            if [ -n "$POLICY_DIR" ] && [ -f "$appended" ]; then
                printf '\n# --- added by the site policy directory ---\n' >> "$rendered"
                cat "$appended" >> "$rendered"
            fi
            printf '%s' "$rendered" ;;
    esac
}
digest() { [ -f "$1" ] && sha256sum "$1" | cut -d' ' -f1 || echo absent; }

# ------------------------------------------------------------------- the plan
# Built once, printed by `status`, executed by `apply`. Both read the same
# list, so what you are shown is exactly what would happen.
PLAN=()
build_plan() {
    PLAN=()
    local src dst mode roles condition rendered current desired

    while IFS=: read -r src dst mode roles condition; do
        [ -z "$src" ] && continue
        wanted_on_role "$roles" || continue
        if ! "$condition"; then
            PLAN+=("skip|$src|$dst|$mode|$EXISTING_LIMITER")
            continue
        fi
        rendered="$(render "$src")"
        current="$(digest "$dst")"
        desired="$(sha256sum "$rendered" | cut -d' ' -f1)"
        if   [ "$current" = absent ];    then PLAN+=("create|$src|$dst|$mode|")
        elif [ "$current" != "$desired" ]; then PLAN+=("update|$src|$dst|$mode|")
        else                                  PLAN+=("keep|$src|$dst|$mode|")
        fi
    done <<< "$DESIRED_STATE"

    for agent in $AGENTFENCE_SHIM_AGENTS; do
        if [ "$(readlink "/opt/agentfence/bin/$agent" 2>/dev/null)" = "$SHIM_TARGET" ]; then
            PLAN+=("keep-link||/opt/agentfence/bin/$agent||")
        else
            PLAN+=("link||/opt/agentfence/bin/$agent||")
        fi
    done
}

plan_has_work() {
    local entry
    for entry in "${PLAN[@]}"; do
        case "${entry%%|*}" in create|update|link) return 0 ;; esac
    done
    return 1
}

print_plan() {
    heading "State ($ROLE node, $(hostname -s))"
    local entry verb dst extra
    for entry in "${PLAN[@]}"; do
        IFS='|' read -r verb _ dst _ extra <<< "$entry"
        case "$verb" in
            keep|keep-link) same   "ok       $dst" ;;
            create)         change "create   $dst" ;;
            update)         change "update   $dst  (edited on this node)" ;;
            link)           change "link     $dst" ;;
            skip)           note   "skipped  $dst  (already handled by: $extra)" ;;
        esac
    done
}

# --------------------------------------------------------------------- checks
preflight() {
    heading "Checks"
    local cap
    # The rendered file, with this site's paths in it - that is what lands on
    # the node, and a site path is exactly what could break it.
    local settings; settings="$(render managed-settings.json)"
    python3 -c "import json;json.load(open('$settings'))" 2>/dev/null \
        && same "the Claude Code policy file is valid" \
        || problem "the Claude Code policy file is not valid JSON - refusing to go on"

    grep -qE '"(Read|Write|Edit)\(/[^/]' "$settings" \
        && problem "a path rule starts with a single slash; that means 'next to the settings file', not '/'" \
        || same "path rules are absolute"

    if [ -n "$POLICY_DIR" ]; then
        note "policy comes from $POLICY_DIR, not only the shipped payload"
        [ -n "$OVERLAY" ] && note "an overlay is merged in; run 'agentfence config' to see what"
    fi

    if [ -z "$AGENTFENCE_SHARED_HOMES" ]; then
        note "no shared home filesystem set; only /home is protected (AGENTFENCE_SHARED_HOMES)"
    else
        same "other users' homes protected under:$AGENTFENCE_SHARED_HOMES"
    fi
    [ -n "$AGENTFENCE_SHARED_WORKSPACES" ] \
        && same "agents may read:$AGENTFENCE_SHARED_WORKSPACES" \
        || note "agents can read only \$HOME; set AGENTFENCE_SHARED_WORKSPACES for shared project space"

    if command -v bwrap >/dev/null 2>&1; then
        same "bwrap is installed"
        find "$(command -v bwrap)" -perm -4000 2>/dev/null | grep -q . \
            && problem "bwrap is setuid; use a build that is not (there have been escalation CVEs)"
    else
        note "bwrap is missing, so Claude Code's sandbox will refuse to start"
    fi

    command -v cplt >/dev/null 2>&1 \
        && same "cplt is installed" \
        || note "cplt is missing, so agents other than Claude Code are not sandboxed"

    if [ "$ROLE" = login ]; then
        [ -n "$EXISTING_LIMITER" ] \
            && note "resource limits are already handled here by: $EXISTING_LIMITER" \
            || same "no other tool is limiting login-node use"
    else
        same "compute node: Slurm owns resource limits, nothing added here"
    fi

    [ -f /sys/fs/cgroup/cgroup.controllers ] \
        && same "cgroups v2" \
        || note "cgroups v1"

    # Does the sandbox actually work here, rather than merely being installed?
    if command -v bwrap >/dev/null 2>&1; then
        bwrap --unshare-all --ro-bind / / /bin/true >/dev/null 2>&1 \
            && same "unprivileged namespaces work" \
            || problem "bwrap cannot create a namespace; check kernel.unprivileged_userns_clone or an AppArmor rule"
    fi

    # Anything already installed must be root-owned, or the policy is advisory.
    if [ -e /etc/claude-code/managed-settings.json ]; then
        [ "$(stat -c %U /etc/claude-code/managed-settings.json 2>/dev/null)" = root ] \
            && same "the installed policy file is owned by root" \
            || problem "the installed policy file is not owned by root; users can edit it"
    fi

    # A cap that is set but not enforced looks fine and does nothing.
    if [ "$ROLE" = login ] && [ -z "$EXISTING_LIMITER" ] && [ "$(id -u)" != 0 ]; then
        cap="$(systemctl show -p MemoryMax --value "user-$(id -u).slice" 2>/dev/null)"
        case "$cap" in
            "")       note "cannot tell whether your session is capped (no systemctl)" ;;
            infinity) note "your own session has no memory cap yet" ;;
            *)        same "your session is capped at $cap" ;;
        esac
    fi
}

# --------------------------------------------------------------------- config
# Prints the settings that a run would actually use, and where each one came
# from. Reads nothing but the config layers, changes nothing, needs no root.
print_config() {
    heading "Settings ($(hostname -s))"
    local key value origin width=0
    for key in $SETTINGS; do
        [ ${#key} -gt $width ] && width=${#key}
    done
    for key in $SETTINGS; do
        value="${!key}"
        origin="$(origin_of "$key")"
        [ -z "$value" ] && value="(unset)"
        printf '  %-*s  %-28s %s%s%s\n' "$width" "$key" "$value" "$C_OK" "$origin" "$C_0"
    done
    say ""
    say "Precedence, highest first: --config, the environment,"
    say "/etc/agentfence/site.env, the built-in defaults."

    heading "Policy"
    if [ -z "$POLICY_DIR" ]; then
        same "shipped policy only (no --policy-dir)"
    else
        say "  site directory: $POLICY_DIR"
        local f
        while IFS=: read -r f _ _ _ _; do
            [ -z "$f" ] && continue
            [ "$f" = site.env ] && continue
            if [ "$(policy_source "$f")" = site ]; then
                change "$f  replaced by the site copy"
            elif [ -f "$POLICY_DIR/$f.append" ]; then
                change "$f  shipped, with $f.append added to it"
            else
                same "$f  shipped"
            fi
        done <<< "$DESIRED_STATE"
        [ -n "$OVERLAY" ] \
            && change "managed-settings.overlay.json  merged into the shipped policy" \
            || same "no overlay"
    fi
    if [ -z "$AGENTFENCE_SHARED_HOMES" ]; then
        say ""
        note "AGENTFENCE_SHARED_HOMES is unset: only /home is treated as other"
        note "people's homes. If this site keeps them elsewhere, set it."
    fi
}

# ---------------------------------------------------------------------- doctor
# Everything `status` checks, plus the two things only the tools themselves can
# answer: whether each shimmed agent is actually installed, and what cplt makes
# of this machine.
#
# cplt doctor inspects the *calling user's* environment - their PATH, their
# $HOME, their agent installs. Run under sudo it reports root's view, which is
# not what any user gets, so it says so rather than implying otherwise.
run_doctor() {
    preflight

    heading "Shims"
    local agent real found
    for agent in $AGENTFENCE_SHIM_AGENTS; do
        found=""
        IFS=:
        for real in $PATH; do
            [ "$real" = "$SHIM_DIR" ] && continue
            [ -x "$real/$agent" ] && { found="$real/$agent"; break; }
        done
        unset IFS
        if [ -n "$found" ]; then
            same "$agent  -> $found"
        else
            note "$agent  not installed here; the shim will say so if run"
        fi
    done

    heading "cplt"
    if ! command -v cplt >/dev/null 2>&1; then
        note "cplt is not installed, so no agent but Claude Code is sandboxed"
        return 0
    fi
    if [ "$(id -u)" = 0 ]; then
        note "running as root: cplt doctor reports root's environment, not a user's"
        note "for what a user sees, run 'agentfence doctor' as that user"
    fi
    say ""
    CPLT_CONFIG="${CPLT_CONFIG:-/etc/agentfence/cplt.toml}" cplt doctor 2>&1 | sed 's/^/  /' \
        || note "cplt doctor reported a problem (above)"
}

# ------------------------------------------------------------------------ init
# Writes the shipped defaults out so an admin has something to edit. This is
# the only way to get a starting point without a source checkout.
#
# It never overwrites: an existing file is left alone and reported. `apply`
# still refuses a --config or --policy-dir that does not exist, because a
# typo in a filename must not quietly become "use the defaults" - that would
# install a weaker policy than the admin believes they asked for.
write_scaffold() {
    local src="$1" dst="$2"
    if [ -e "$dst" ]; then
        same "kept     $dst  (already exists)"
        return 0
    fi
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst" && change "wrote    $dst" || problem "could not write $dst"
}

do_init() {
    [ -n "$CONFIG_FILE" ] || [ -n "$POLICY_DIR_ARG" ] \
        || die "init needs --config FILE, --policy-dir DIR, or both"

    heading "Init"

    if [ -n "$CONFIG_FILE" ]; then
        write_scaffold "$WORK/agentfence.conf.example" "$CONFIG_FILE"
    fi

    if [ -n "$POLICY_DIR_ARG" ]; then
        mkdir -p "$POLICY_DIR_ARG"
        local f
        # Every shipped policy file, so an admin can see what they are
        # overriding before they override it.
        while IFS=: read -r f _ _ _ _; do
            case "$f" in ''|site.env) continue ;; esac
            write_scaffold "$WORK/$f" "$POLICY_DIR_ARG/$f.shipped"
        done <<< "$DESIRED_STATE"

        if [ ! -e "$POLICY_DIR_ARG/managed-settings.overlay.json" ]; then
            cat > "$POLICY_DIR_ARG/managed-settings.overlay.json" <<'OVERLAY'
{
  "permissions": {
    "deny": []
  }
}
OVERLAY
            change "wrote    $POLICY_DIR_ARG/managed-settings.overlay.json"
        else
            same "kept     $POLICY_DIR_ARG/managed-settings.overlay.json  (already exists)"
        fi

        if [ ! -e "$POLICY_DIR_ARG/README" ]; then
            cat > "$POLICY_DIR_ARG/README" <<'SITEREADME'
Site policy for agentfence.

  agentfence apply --policy-dir THIS_DIRECTORY

The *.shipped files are copies of what agentfence installs by default. They
are reference only and are not read - delete them if you like. To change
something, create a file next to them:

  <name>                          replaces the shipped file outright
  <name>.append                   adds lines to the end of the shipped file
  managed-settings.overlay.json   merged into the Claude Code policy
  desired-state                   extra files of your own, one per line:
                                    src:/absolute/dest:0644:login,compute:always

Prefer .append and the overlay over replacing. A replaced file stops picking
up later changes to the shipped one, including fixes.

An overlay can add but not remove: lists are appended to, so it cannot drop a
shipped rule by leaving it out. It also cannot switch off the sandbox or
re-enable permission bypass - those are refused before anything is written.

See what any of it does, changing nothing:

  agentfence config --policy-dir THIS_DIRECTORY
SITEREADME
            change "wrote    $POLICY_DIR_ARG/README"
        else
            same "kept     $POLICY_DIR_ARG/README  (already exists)"
        fi
    fi

    say ""
    say "Edit those, then check with:"
    [ -n "$POLICY_DIR_ARG" ] \
        && say "  agentfence config --policy-dir $POLICY_DIR_ARG" \
        || say "  agentfence config --config $CONFIG_FILE"
}

# ---------------------------------------------------------------------- apply
confirm() {
    [ "$ASSUME_YES" = 1 ] && return 0
    printf '\n%sApply this to %s? [y/N] %s' "$C_B" "$(hostname -s)" "$C_0"
    read -r answer
    case "$answer" in y|Y|yes) return 0 ;; *) say "Nothing done."; exit $E_OK ;; esac
}

install_packages() {
    [ "$DO_PACKAGES" = 1 ] || return 0
    command -v bwrap >/dev/null 2>&1 && command -v cplt >/dev/null 2>&1 && return 0
    command -v apt-get >/dev/null 2>&1 || {
        note "not a Debian-family system; install bubblewrap and cplt yourself"; return 0; }

    heading "Packages"
    command -v bwrap >/dev/null 2>&1 || {
        apt-get install -y bubblewrap >/dev/null 2>&1 \
            && change "installed bubblewrap" || problem "could not install bubblewrap"; }

    command -v cplt >/dev/null 2>&1 || {
        # navikt/cplt: the sandbox for agents other than Claude Code.
        if curl -fsSL https://navikt.github.io/apt/keyring/navikt-archive-keyring.gpg \
             -o /usr/share/keyrings/navikt-archive-keyring.gpg 2>/dev/null; then
            printf 'deb [signed-by=/usr/share/keyrings/navikt-archive-keyring.gpg] https://navikt.github.io/apt stable main\n' \
                > /etc/apt/sources.list.d/navikt.list
            apt-get update -qq >/dev/null 2>&1
            apt-get install -y cplt >/dev/null 2>&1 \
                && change "installed cplt" || problem "could not install cplt"
        else
            problem "could not fetch the cplt signing key"
        fi; }
}

execute_plan() {
    heading "Applying"
    local entry verb src dst mode rendered touched_units=0 touched_audit=0
    for entry in "${PLAN[@]}"; do
        IFS='|' read -r verb src dst mode _ <<< "$entry"
        case "$verb" in
            create|update)
                rendered="$(render "$src")"
                mkdir -p "$(dirname "$dst")"
                if install -o root -g root -m "$mode" "$rendered" "$dst"; then
                    change "$verb  $dst"
                    case "$dst" in
                        */systemd/*)   touched_units=1 ;;
                        */audit/*)     touched_audit=1 ;;
                    esac
                else
                    problem "could not write $dst"
                fi ;;
            link)
                mkdir -p "$(dirname "$dst")"
                ln -sfn "$SHIM_TARGET" "$dst" \
                    && change "link    $dst" || problem "could not link $dst" ;;
        esac
    done

    if [ "$touched_units" = 1 ]; then
        systemctl daemon-reload 2>/dev/null \
            && change "reloaded systemd" || note "could not reload systemd"
    fi
    if [ "$touched_audit" = 1 ] && command -v augenrules >/dev/null 2>&1; then
        augenrules --load >/dev/null 2>&1 \
            && change "reloaded the audit rules" || note "could not reload the audit rules"
    fi
}

remove_everything() {
    heading "Removing"
    local entry dst
    for entry in "${PLAN[@]}"; do
        IFS='|' read -r _ _ dst _ _ <<< "$entry"
        [ -e "$dst" ] || [ -L "$dst" ] || continue
        rm -f "$dst" && change "removed $dst" || problem "could not remove $dst"
    done
    rm -f "$SHIM_TARGET"
    systemctl daemon-reload 2>/dev/null
    command -v augenrules >/dev/null 2>&1 && augenrules --load >/dev/null 2>&1
    say ""
    say "Removed. bubblewrap and cplt were left installed."
}

# ------------------------------------------------------------------------ run
case "$ACTION" in
    doctor)
        run_doctor
        exit "$([ "$FAILED" = 1 ] && echo $E_FAIL || echo $E_OK)" ;;

    init)
        do_init
        exit "$([ "$FAILED" = 1 ] && echo $E_FAIL || echo $E_OK)" ;;

    config)
        print_config
        exit $E_OK ;;

    status)
        preflight; build_plan; print_plan
        say ""
        if plan_has_work; then
            say "This node does not match. Run 'apply' to fix it."
            exit $E_DRIFT
        fi
        say "This node matches. Nothing to do."
        exit "$([ "$FAILED" = 1 ] && echo $E_FAIL || echo $E_OK)" ;;

    apply)
        [ "$(id -u)" = 0 ] || die "apply must be run as root"
        preflight
        [ "$FAILED" = 0 ] || die "checks failed; nothing was changed"
        build_plan; print_plan
        if ! plan_has_work; then
            say ""; say "This node already matches. Nothing to do."; exit $E_OK
        fi
        confirm
        install_packages
        execute_plan
        say ""
        say "Done. Users pick up the new PATH and CPLT_CONFIG at their next login."
        say "Check any time with: agentfence"
        exit "$([ "$FAILED" = 1 ] && echo $E_FAIL || echo $E_OK)" ;;

    uninstall)
        [ "$(id -u)" = 0 ] || die "uninstall must be run as root"
        build_plan; print_plan; confirm; remove_everything
        exit "$([ "$FAILED" = 1 ] && echo $E_FAIL || echo $E_OK)" ;;
esac
