#!/usr/bin/env bash
# agentfence - guardrails for AI coding agents on shared Linux hosts.
#
# Self-contained. Copy this one file to a node and run it. Needs bash,
# coreutils and python3; nothing else, and no network access.
#
#   ./agentfence              what is on this node vs what should be
#   ./agentfence apply        make the node match. Asks first.
#   ./agentfence uninstall    remove everything it installed
#
#   --yes           do not ask
#   --role login|compute|auto        default auto
#   --nodes "a b c" do the same on those hosts over ssh
#   --no-packages   do not install bubblewrap or cplt
#
# Exit status: 0 the node matches, 1 it does not (status only), 2 something
# went wrong. So `agentfence || alert` works from cron.
#
# Built from the agentfence repository. Regenerate with `make dist`;
# do not edit this file by hand.
set -uo pipefail

VERSION="@@VERSION@@"
BUILT="@@BUILT@@"

readonly E_OK=0 E_DRIFT=1 E_FAIL=2

ACTION=status ROLE=auto ASSUME_YES=0 DO_PACKAGES=1 NODES=""
WORK="" FAILED=0

# --------------------------------------------------------------------- output
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
    C_OK=$'\033[32m'; C_CHG=$'\033[33m'; C_ERR=$'\033[31m'; C_B=$'\033[1m'; C_0=$'\033[0m'
else
    C_OK=""; C_CHG=""; C_ERR=""; C_B=""; C_0=""
fi
say()     { printf '%s\n' "$*"; }
heading() { printf '\n%s%s%s\n' "$C_B" "$*" "$C_0"; }
same()    { printf '  %s=%s %s\n'  "$C_OK"  "$C_0" "$*"; }
change()  { printf '  %s>%s %s\n'  "$C_CHG" "$C_0" "$*"; }
note()    { printf '  %s-%s %s\n'  "$C_CHG" "$C_0" "$*"; }
problem() { printf '  %s!%s %s\n'  "$C_ERR" "$C_0" "$*" >&2; FAILED=1; }
die()     { printf '%s!%s %s\n'    "$C_ERR" "$C_0" "$*" >&2; exit $E_FAIL; }

trap '[ -n "$WORK" ] && rm -rf "$WORK"' EXIT

# ----------------------------------------------------------------------- args
while [ $# -gt 0 ]; do
    case "$1" in
        status|apply|uninstall) ACTION="$1" ;;
        --role)        ROLE="${2:?--role needs a value}"; shift ;;
        --nodes)       NODES="${2:?--nodes needs a value}"; shift ;;
        --yes|-y)      ASSUME_YES=1 ;;
        --no-packages) DO_PACKAGES=0 ;;
        --version)     say "agentfence $VERSION (built $BUILT)"; exit $E_OK ;;
        -h|--help)     sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'; exit $E_OK ;;
        *)             die "unknown argument: $1" ;;
    esac
    shift
done

# ------------------------------------------------------------ fan out to nodes
if [ -n "$NODES" ]; then
    rc=$E_OK
    for host in $NODES; do
        heading "=== $host ==="
        if ! scp -q "$0" "$host:/tmp/agentfence"; then
            problem "$host: could not copy the script"; rc=$E_FAIL; continue
        fi
        ssh -t "$host" "sudo bash /tmp/agentfence $ACTION --role $ROLE \
            $([ "$ASSUME_YES" = 1 ] && echo --yes) \
            $([ "$DO_PACKAGES" = 0 ] && echo --no-packages); \
            s=\$?; rm -f /tmp/agentfence; exit \$s"
        case "$?" in 0) ;; 1) [ "$rc" = "$E_OK" ] && rc=$E_DRIFT ;; *) rc=$E_FAIL ;; esac
    done
    exit $rc
fi

# ------------------------------------------------------------- unpack payload
WORK="$(mktemp -d)" || die "could not create a temporary directory"
awk 'f{print} /^__PAYLOAD__$/{f=1}' "$0" | base64 -d | tar -xz -C "$WORK" \
    || die "the payload is corrupt; copy the script again"

# --------------------------------------------------------------- site layout
# Where this site keeps shared home directories, read-only software trees and
# project space. These differ per machine and there is no sane default, so
# they are settings, not constants in the payload.
#
# Precedence: the environment wins, otherwise whatever a previous `apply`
# recorded, otherwise empty. The recorded file is what makes `status` from
# cron stable - without it a run with no variables set would report drift
# against the node every time and the exit code would be useless.
SITE_ENV=/etc/agentfence/site.env
if [ -r "$SITE_ENV" ]; then
    # Only our own keys, and only KEY=value - never source an arbitrary file
    # as root.
    while IFS='=' read -r key value; do
        case "$key" in
            AGENTFENCE_SHARED_HOMES|AGENTFENCE_SHARED_APPS|\
            AGENTFENCE_SHARED_WORKSPACES|AGENTFENCE_SITE_NAME|\
            AGENTFENCE_MEMORY_HIGH|AGENTFENCE_MEMORY_MAX|\
            AGENTFENCE_CPU_QUOTA|AGENTFENCE_TASKS_MAX)
                value="${value%\"}"; value="${value#\"}"
                [ -z "${!key:-}" ] && export "$key=$value" ;;
        esac
    done < "$SITE_ENV"
fi

export AGENTFENCE_SHARED_HOMES="${AGENTFENCE_SHARED_HOMES:-}"
export AGENTFENCE_SHARED_APPS="${AGENTFENCE_SHARED_APPS:-}"
export AGENTFENCE_SHARED_WORKSPACES="${AGENTFENCE_SHARED_WORKSPACES:-}"
export AGENTFENCE_SITE_NAME="${AGENTFENCE_SITE_NAME:-This shared machine}"
export AGENTFENCE_MEMORY_HIGH="${AGENTFENCE_MEMORY_HIGH:-8G}"
export AGENTFENCE_MEMORY_MAX="${AGENTFENCE_MEMORY_MAX:-16G}"
export AGENTFENCE_CPU_QUOTA="${AGENTFENCE_CPU_QUOTA:-400%}"
export AGENTFENCE_TASKS_MAX="${AGENTFENCE_TASKS_MAX:-4096}"

# Written back out so the next run, by anyone, sees the same settings.
{
    printf '# Managed by agentfence. Written by `agentfence apply`.\n'
    printf '# Change a value by re-running apply with it in the environment:\n'
    printf '#   AGENTFENCE_SHARED_HOMES=/shared/home sudo -E agentfence apply\n'
    for key in AGENTFENCE_SITE_NAME AGENTFENCE_SHARED_HOMES AGENTFENCE_SHARED_APPS \
               AGENTFENCE_SHARED_WORKSPACES AGENTFENCE_MEMORY_HIGH \
               AGENTFENCE_MEMORY_MAX AGENTFENCE_CPU_QUOTA AGENTFENCE_TASKS_MAX; do
        printf '%s="%s"\n' "$key" "${!key}"
    done
} > "$WORK/site.env"

# Fail before anything is printed or planned: a site path that cannot be used
# makes every later check meaningless.
python3 "$WORK/render-settings.py" "$WORK/managed-settings.json" \
    > "$WORK/settings.rendered" \
    || die "check the AGENTFENCE_SHARED_* paths above; nothing was changed"

# ----------------------------------------------------------------------- node
detect_role() {
    if command -v scontrol >/dev/null 2>&1 \
       && scontrol show node "$(hostname -s)" >/dev/null 2>&1; then
        echo compute
    elif systemctl is-active --quiet slurmd 2>/dev/null; then
        echo compute
    else
        echo login
    fi
}
[ "$ROLE" = auto ] && ROLE="$(detect_role)"
case "$ROLE" in login|compute) ;; *) die "--role must be login, compute or auto" ;; esac

# Something else already limits what one user can take on a login node
# (Arbiter2, Arbiter3, cgroup-warden, or a hand-written drop-in). If so we
# leave resource limits alone: two things managing the same slice is worse
# than one. Slurm is not a candidate - a login-node session is in no job.
find_existing_limiter() {
    local found=""
    systemctl list-unit-files 2>/dev/null \
        | grep -qE '^(arbiter2?|arbiter|cgroup-warden)\.service' && found="$found arbiter/cgroup-warden"
    for binary in arbiter arbiter2 cgroup-warden; do
        command -v "$binary" >/dev/null 2>&1 && found="$found $binary"
    done
    for dir in /etc/arbiter2 /etc/arbiter /etc/cgroup-warden; do
        [ -d "$dir" ] && found="$found $dir"
    done
    for f in /etc/systemd/system/user-.slice.d/*.conf; do
        [ -e "$f" ] || continue
        case "$f" in *50-agentfence-user-limits.conf) continue ;; esac
        found="$found $f"
    done
    printf '%s' "${found# }"
}
EXISTING_LIMITER="$(find_existing_limiter)"

# ------------------------------------------------------------- desired state
# One table. Each line: payload-file : destination : mode : roles : condition
# `condition` names a function that must succeed for the file to be wanted.
DESIRED_STATE="
site.env:/etc/agentfence/site.env:0644:login,compute:always
managed-settings.json:/etc/claude-code/managed-settings.json:0644:login,compute:always
50-agentfence-audit.rules:/etc/audit/rules.d/50-agentfence-audit.rules:0640:login,compute:always
cplt-config.toml:/etc/agentfence/cplt.toml:0644:login,compute:always
profile.d-agentfence.sh:/etc/profile.d/10-agentfence.sh:0644:login,compute:always
bin/agentfence-shim:/opt/agentfence/bin/agentfence-shim:0755:login,compute:always
50-agentfence-user-limits.conf:/etc/systemd/system/user-.slice.d/50-agentfence-user-limits.conf:0644:login:no_existing_limiter
50-agentfence-root-exempt.conf:/etc/systemd/system/user-0.slice.d/50-agentfence-root-exempt.conf:0644:login:no_existing_limiter
"
SHIM_AGENTS="copilot opencode goose"
SHIM_TARGET=/opt/agentfence/bin/agentfence-shim

always()             { return 0; }
no_existing_limiter() { [ -z "$EXISTING_LIMITER" ]; }
wanted_on_role()      { case ",$1," in *",$ROLE,"*) return 0 ;; *) return 1 ;; esac; }

# Per-site values come from the environment rather than from editing the
# payload. One rendered file per source - a single shared temporary name would
# have two templated files overwrite each other.
render() {
    local source="$WORK/$1" rendered="$WORK/.rendered.${1//\//_}"
    case "$1" in
        managed-settings.json)
            # Built once at startup. Rendering here instead would put `die`
            # inside a command substitution, where it exits only the subshell
            # and the run carries on with an empty filename.
            printf '%s' "$WORK/settings.rendered" ;;
        site.env)
            printf '%s' "$WORK/site.env" ;;
        *)
            if grep -q '{{' "$source" 2>/dev/null; then
                sed -e "s|{{ memory_high }}|$AGENTFENCE_MEMORY_HIGH|g" \
                    -e "s|{{ memory_max }}|$AGENTFENCE_MEMORY_MAX|g" \
                    -e "s|{{ cpu_quota }}|$AGENTFENCE_CPU_QUOTA|g" \
                    -e "s|{{ tasks_max }}|$AGENTFENCE_TASKS_MAX|g" \
                    "$source" > "$rendered"
                printf '%s' "$rendered"
            else
                printf '%s' "$source"
            fi ;;
    esac
}
digest() { [ -f "$1" ] && sha256sum "$1" | cut -d' ' -f1 || echo absent; }

# ------------------------------------------------------------------- the plan
# Built once, printed by `status`, executed by `apply`. Both read the same
# list, so what you are shown is exactly what would happen.
PLAN=()
build_plan() {
    PLAN=()
    local src dst mode roles condition rendered current desired

    while IFS=: read -r src dst mode roles condition; do
        [ -z "$src" ] && continue
        wanted_on_role "$roles" || continue
        if ! "$condition"; then
            PLAN+=("skip|$src|$dst|$mode|$EXISTING_LIMITER")
            continue
        fi
        rendered="$(render "$src")"
        current="$(digest "$dst")"
        desired="$(sha256sum "$rendered" | cut -d' ' -f1)"
        if   [ "$current" = absent ];    then PLAN+=("create|$src|$dst|$mode|")
        elif [ "$current" != "$desired" ]; then PLAN+=("update|$src|$dst|$mode|")
        else                                  PLAN+=("keep|$src|$dst|$mode|")
        fi
    done <<< "$DESIRED_STATE"

    for agent in $SHIM_AGENTS; do
        if [ "$(readlink "/opt/agentfence/bin/$agent" 2>/dev/null)" = "$SHIM_TARGET" ]; then
            PLAN+=("keep-link||/opt/agentfence/bin/$agent||")
        else
            PLAN+=("link||/opt/agentfence/bin/$agent||")
        fi
    done
}

plan_has_work() {
    local entry
    for entry in "${PLAN[@]}"; do
        case "${entry%%|*}" in create|update|link) return 0 ;; esac
    done
    return 1
}

print_plan() {
    heading "State ($ROLE node, $(hostname -s))"
    local entry verb dst extra
    for entry in "${PLAN[@]}"; do
        IFS='|' read -r verb _ dst _ extra <<< "$entry"
        case "$verb" in
            keep|keep-link) same   "ok       $dst" ;;
            create)         change "create   $dst" ;;
            update)         change "update   $dst  (edited on this node)" ;;
            link)           change "link     $dst" ;;
            skip)           note   "skipped  $dst  (already handled by: $extra)" ;;
        esac
    done
}

# --------------------------------------------------------------------- checks
preflight() {
    heading "Checks"
    local cap
    # The rendered file, with this site's paths in it - that is what lands on
    # the node, and a site path is exactly what could break it.
    local settings; settings="$(render managed-settings.json)"
    python3 -c "import json;json.load(open('$settings'))" 2>/dev/null \
        && same "the Claude Code policy file is valid" \
        || problem "the Claude Code policy file is not valid JSON - refusing to go on"

    grep -qE '"(Read|Write|Edit)\(/[^/]' "$settings" \
        && problem "a path rule starts with a single slash; that means 'next to the settings file', not '/'" \
        || same "path rules are absolute"

    if [ -z "$AGENTFENCE_SHARED_HOMES" ]; then
        note "no shared home filesystem set; only /home is protected (AGENTFENCE_SHARED_HOMES)"
    else
        same "other users' homes protected under:$AGENTFENCE_SHARED_HOMES"
    fi
    [ -n "$AGENTFENCE_SHARED_WORKSPACES" ] \
        && same "agents may read:$AGENTFENCE_SHARED_WORKSPACES" \
        || note "agents can read only \$HOME; set AGENTFENCE_SHARED_WORKSPACES for shared project space"

    if command -v bwrap >/dev/null 2>&1; then
        same "bwrap is installed"
        find "$(command -v bwrap)" -perm -4000 2>/dev/null | grep -q . \
            && problem "bwrap is setuid; use a build that is not (there have been escalation CVEs)"
    else
        note "bwrap is missing, so Claude Code's sandbox will refuse to start"
    fi

    command -v cplt >/dev/null 2>&1 \
        && same "cplt is installed" \
        || note "cplt is missing, so agents other than Claude Code are not sandboxed"

    if [ "$ROLE" = login ]; then
        [ -n "$EXISTING_LIMITER" ] \
            && note "resource limits are already handled here by: $EXISTING_LIMITER" \
            || same "no other tool is limiting login-node use"
    else
        same "compute node: Slurm owns resource limits, nothing added here"
    fi

    [ -f /sys/fs/cgroup/cgroup.controllers ] \
        && same "cgroups v2" \
        || note "cgroups v1"

    # Does the sandbox actually work here, rather than merely being installed?
    if command -v bwrap >/dev/null 2>&1; then
        bwrap --unshare-all --ro-bind / / /bin/true >/dev/null 2>&1 \
            && same "unprivileged namespaces work" \
            || problem "bwrap cannot create a namespace; check kernel.unprivileged_userns_clone or an AppArmor rule"
    fi

    # Anything already installed must be root-owned, or the policy is advisory.
    if [ -e /etc/claude-code/managed-settings.json ]; then
        [ "$(stat -c %U /etc/claude-code/managed-settings.json 2>/dev/null)" = root ] \
            && same "the installed policy file is owned by root" \
            || problem "the installed policy file is not owned by root; users can edit it"
    fi

    # A cap that is set but not enforced looks fine and does nothing.
    if [ "$ROLE" = login ] && [ -z "$EXISTING_LIMITER" ] && [ "$(id -u)" != 0 ]; then
        cap="$(systemctl show -p MemoryMax --value "user-$(id -u).slice" 2>/dev/null)"
        case "$cap" in
            "")       note "cannot tell whether your session is capped (no systemctl)" ;;
            infinity) note "your own session has no memory cap yet" ;;
            *)        same "your session is capped at $cap" ;;
        esac
    fi
}

# ---------------------------------------------------------------------- apply
confirm() {
    [ "$ASSUME_YES" = 1 ] && return 0
    printf '\n%sApply this to %s? [y/N] %s' "$C_B" "$(hostname -s)" "$C_0"
    read -r answer
    case "$answer" in y|Y|yes) return 0 ;; *) say "Nothing done."; exit $E_OK ;; esac
}

install_packages() {
    [ "$DO_PACKAGES" = 1 ] || return 0
    command -v bwrap >/dev/null 2>&1 && command -v cplt >/dev/null 2>&1 && return 0
    command -v apt-get >/dev/null 2>&1 || {
        note "not a Debian-family system; install bubblewrap and cplt yourself"; return 0; }

    heading "Packages"
    command -v bwrap >/dev/null 2>&1 || {
        apt-get install -y bubblewrap >/dev/null 2>&1 \
            && change "installed bubblewrap" || problem "could not install bubblewrap"; }

    command -v cplt >/dev/null 2>&1 || {
        # navikt/cplt: the sandbox for agents other than Claude Code.
        if curl -fsSL https://navikt.github.io/apt/keyring/navikt-archive-keyring.gpg \
             -o /usr/share/keyrings/navikt-archive-keyring.gpg 2>/dev/null; then
            printf 'deb [signed-by=/usr/share/keyrings/navikt-archive-keyring.gpg] https://navikt.github.io/apt stable main\n' \
                > /etc/apt/sources.list.d/navikt.list
            apt-get update -qq >/dev/null 2>&1
            apt-get install -y cplt >/dev/null 2>&1 \
                && change "installed cplt" || problem "could not install cplt"
        else
            problem "could not fetch the cplt signing key"
        fi; }
}

execute_plan() {
    heading "Applying"
    local entry verb src dst mode rendered touched_units=0 touched_audit=0
    for entry in "${PLAN[@]}"; do
        IFS='|' read -r verb src dst mode _ <<< "$entry"
        case "$verb" in
            create|update)
                rendered="$(render "$src")"
                mkdir -p "$(dirname "$dst")"
                if install -o root -g root -m "$mode" "$rendered" "$dst"; then
                    change "$verb  $dst"
                    case "$dst" in
                        */systemd/*)   touched_units=1 ;;
                        */audit/*)     touched_audit=1 ;;
                    esac
                else
                    problem "could not write $dst"
                fi ;;
            link)
                mkdir -p "$(dirname "$dst")"
                ln -sfn "$SHIM_TARGET" "$dst" \
                    && change "link    $dst" || problem "could not link $dst" ;;
        esac
    done

    if [ "$touched_units" = 1 ]; then
        systemctl daemon-reload 2>/dev/null \
            && change "reloaded systemd" || note "could not reload systemd"
    fi
    if [ "$touched_audit" = 1 ] && command -v augenrules >/dev/null 2>&1; then
        augenrules --load >/dev/null 2>&1 \
            && change "reloaded the audit rules" || note "could not reload the audit rules"
    fi
}

remove_everything() {
    heading "Removing"
    local entry dst
    for entry in "${PLAN[@]}"; do
        IFS='|' read -r _ _ dst _ _ <<< "$entry"
        [ -e "$dst" ] || [ -L "$dst" ] || continue
        rm -f "$dst" && change "removed $dst" || problem "could not remove $dst"
    done
    rm -f "$SHIM_TARGET"
    systemctl daemon-reload 2>/dev/null
    command -v augenrules >/dev/null 2>&1 && augenrules --load >/dev/null 2>&1
    say ""
    say "Removed. bubblewrap and cplt were left installed."
}

# ------------------------------------------------------------------------ run
case "$ACTION" in
    status)
        preflight; build_plan; print_plan
        say ""
        if plan_has_work; then
            say "This node does not match. Run 'apply' to fix it."
            exit $E_DRIFT
        fi
        say "This node matches. Nothing to do."
        exit "$([ "$FAILED" = 1 ] && echo $E_FAIL || echo $E_OK)" ;;

    apply)
        [ "$(id -u)" = 0 ] || die "apply must be run as root"
        preflight
        [ "$FAILED" = 0 ] || die "checks failed; nothing was changed"
        build_plan; print_plan
        if ! plan_has_work; then
            say ""; say "This node already matches. Nothing to do."; exit $E_OK
        fi
        confirm
        install_packages
        execute_plan
        say ""
        say "Done. Users pick up the new PATH and CPLT_CONFIG at their next login."
        say "Check any time with: agentfence"
        exit "$([ "$FAILED" = 1 ] && echo $E_FAIL || echo $E_OK)" ;;

    uninstall)
        [ "$(id -u)" = 0 ] || die "uninstall must be run as root"
        build_plan; print_plan; confirm; remove_everything
        exit "$([ "$FAILED" = 1 ] && echo $E_FAIL || echo $E_OK)" ;;
esac
